development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:c577263195dd75c4cf544d194fb6f8f1@dory.redistogo.com:11913/
  channel_prefix: message_me_production
